[package]
name = "karlobii/framelink"
version = "1.0.1"
description = "Links frames and buttons with optional animations and one at a time menu management. Includes bulk-link and custom tweens." 
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["karlobii"]
license = "MIT"
repository = "https://github.com/karlobii/FrameLink"

[dependencies]
